#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=02:40:00
#SBATCH --output=output/success/out-%x.%A.out
#SBATCH --error=output/error/out-%x.%A.err

module purge
module load 2023
module load Anaconda3/2023.07-2

cd $HOME/open_clip/

# conda create -n memory_clip python=3.11 -y -c anaconda

source activate memory_clip

pip install torch==2.5.0 torchvision==0.20.0 torchaudio==2.5.0 xformers --index-url https://download.pytorch.org/whl/cu121
# conda install pytorch==2.5.0 torchvision==0.20.0 torchaudio==2.5.0 pytorch-cuda=12.1 -c pytorch -c nvidia

pip install ninja

echo "*********Installing requirements of OpenAI CLIP********"
pip install --requirement requirements.txt

echo "*********Installing requirements of Meta-Memory********"
pip install --requirement requirements_2.txt

echo "*********Installing requirements of OpenAI CLIP-Training********"
pip install --requirement requirements-training.txt

# python -c "import torch; print(f'CUDA available: {torch.cuda.is_available()}'); print(f'PyTorch CUDA version: {torch.version.cuda}')"
