#!/bin/bash

#SBATCH --partition=gpu_a100            # or gpu_a100 (cpu:72)
#SBATCH --gpus=1                        # Max GPUs per node (4)
#SBATCH --job-name=DistillCLIPTeacher_sharegpt4v  # Job name
#SBATCH --ntasks=1                      # 1 task (total)
#SBATCH --cpus-per-task=18           # ~16-18 CPUs per GPU (64/4 -> gpu_h100 or 72/4 -> gpu_a100)
#SBATCH --time=01:50:00         # Max allowed time (120 hours)
#SBATCH --output=output/success/out-%x.%A.out
#SBATCH --error=output/error/out-%x.%A.err


#  SBATCH --mem=480G                  # Max memory per node (480G for gpu_a100, 720G for gpu_h100)
module purge
module load 2023
module load Anaconda3/2023.07-2

cd $HOME/open_clip/

source activate memory_clip

# SBATCH --mem=280G                   # 700G (gpu_h100) or 480G (gpu_a100)

# export LD_LIBRARY_PATH=/home/aibrahimi/.conda/envs/memory_clip/lib/python3.11/site-packages/nvidia/nccl/lib:$LD_LIBRARY_PATH
# ---NCCL Environment Variables---
# export NCCL_IB_TIMEOUT=24 # Increase from default 22 to 24 for InfiniBand
# export NCCL_DEBUG=WARN  # Not "INFO", Critical for error detection.
# export NCCL_DEBUG_SUBSYS=COLL,GRAPH # Filters logs to collective operations and communication graphs.
# export NCCL_LAUNCH_MODE=GROUP # Groups NCCL operations for efficiency.
# export NCCL_ASYNC_ERROR_HANDLING=1 # Enable async error handling
# # export NCCL_P2P_DISABLE=1
# # export NCCL_IB_DISABLE=1
# export NCCL_COLLNET_ENABLE=0 # Disables CollNet (collective network optimizations), which can cause hangs in some topologies.
# export NCCL_SHM_DISABLE=1 #Disables shared memory for NCCL, forcing it to use network/sockets. Helps isolate shared memory bugs.
#---------------------------------

export TORCH_DISTRIBUTED_DEBUG=DETAIL # Detailed PyTorch distributed logs
# export CUDA_LAUNCH_BLOCKING=1

# (72 CPUs / 4 processes = 18 CPUs per process)
# If args.workers is 8, then 18 - 8 = 10 threads for PyTorch ops per process.
# export OMP_NUM_THREADS=10 # Adjust based on args.workers
# echo "OMP_NUM_THREADS: $OMP_NUM_THREADS"

echo "CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"
echo "SLURM_LOCAL_RANK: $SLURM_LOCAL_RANK"
echo "SLURM_PROCID: $SLURM_PROCID"
echo "WORLD_SIZE: $WORLD_SIZE"

#interactive node 
# srun --partition=gpu --gpus=1 --ntasks=1 --cpus-per-task=18 --time=01:00:00 --pty bash -i


# salloc -w gcn59 -N 1 -n 1 -t 00:30:00 -p gpu_a100
#You could request 2 GPUs (--gpus-per-node=2) without increasing the price.
#--train-num-sample => total_samples=$(grep -rh "successes" mscoco/*_stats.json | awk '{sum += $2} END {print sum}')
# --resume="/projects/0/prjs1465/logs/2025_03_25-00_51_04-model_ViT-B-16-lr_0.001-b_128-j_8-p_amp_bf16/checkpoints/epoch_1.pt" \ #FIXME: resume training from checkpoint
# --precision amp_bf16 \

# --train-data="/scratch-shared/mscoco/mscoco/{00000..00047}.tar" \
# --val-data="/scratch-shared/mscoco/mscoco/{00048..00059}.tar"  \
#  --dataset-type=webdataset \
# --train-num-samples 591753 \
# --logs="/scratch-shared/open_clip_memory" 

# --train-data "/projects/0/prjs1465/ShareGPT4V/sharegpt4v/share-captioner_coco_lcs_sam_1246k_1107_train.csv" \
# --val-data "/projects/0/prjs1465/ShareGPT4V/sharegpt4v/share-captioner_coco_lcs_sam_1246k_1107_val.csv" \
# --dataset-type=csv \

#ShareGPT4V dataset (Shard version)
# --train-data="/projects/0/prjs1465/ShareGPT4V/wds_sharegpt4v/train/{000000..000125}.tar" \
# --val-data="/projects/0/prjs1465/ShareGPT4V/wds_sharegpt4v/val/{000000..000001}.tar"  \
# --train-num-samples 1245902 \
# --val-num-samples 2000 \

# torchrun --nproc_per_node 3 -m src.open_clip_train.main_distill_memory -- \
#     --save-frequency 1 \
#     --train-data="/projects/0/prjs1465/ShareGPT4V/wds_mscoco/mscoco_train/{00000..00059}.tar" \
#     --val-data="/projects/0/prjs1465/ShareGPT4V/wds_mscoco/mscoco_val/{00000..00002}.tar"  \
#     --train-num-samples 591753 \
#     --val-num-samples 25014 \
#     --dataset-type=webdataset \
#     --use-memory \
#     --warmup 1000 \
#     --batch-size=20  \
#     --accum-freq 4 \
#     --lr=5e-4 \
#     --wd=0.1 \
#     --epochs=10 \
#     --workers=2 \
#     --grad-checkpointing \
#     --model ViT-B-16 \
#     --precision amp_bf16 \
#     --pretrained "openai" \
#     --report-to wandb \
#     --wandb-project-name "memory-open-clip" \
#     --loss-type "cosine" \
#     --logs="/projects/0/prjs1465/logs" \
#     --log-every-n-steps 100 


# ------ Evaluation of the teacher model (baseline) without memory ------

# -- MSCOCO dataset (Shard version)
# torchrun --nproc_per_node 1 \
#     --rdzv-id=$SLURM_JOB_ID \
#     -m src.open_clip_train.main -- \
#     --val-data="/scratch-shared/mscoco/mscoco_val/{00000..00002}.tar" \
#     --dataset_name "mscoco" \
#     --val-num-samples 25014 \
#     --dataset-type=webdataset \
#     --model ViT-B-16 \
#     --pretrained "openai" \
#     --precision amp_bf16 \
#     --batch-size=16  \
#     --workers=2 \
#     --epochs=0 \
#     --logs="/projects/0/prjs1465/logs/teacher_baseline_eval" \
#     --report-to "none" \

# -- ShareGPT4V dataset (Shard version)

# -- Evaluation of the teacher model (baseline) without memory on ShareGPT4V dataset ------
torchrun --nproc_per_node 1 \
    --rdzv-id=$SLURM_JOB_ID \
    -m src.open_clip_train.main -- \
    --val-data="/projects/0/prjs1465/ShareGPT4V/wds_sharegpt4v/val_1/000000.tar" \
    --dataset_name "sharegpt4v" \
    --val-num-samples 1000 \
    --dataset-type=webdataset \
    --model ViT-B-16 \
    --pretrained "openai" \
    --precision amp_bf16 \
    --batch-size=16  \
    --workers=2 \
    --epochs=0 \
    --logs="/projects/0/prjs1465/logs/teacher_baseline_eval" \
    --report-to "none" \

# ------ Evaluation of the student model with memory on ShareGPT4V dataset ------
# torchrun --nproc_per_node 1 \
#     --rdzv-id=$SLURM_JOB_ID \
#     -m src.open_clip_train.main_distill_memory -- \
#     --resume="/projects/0/prjs1465/logs/2025_05_29-13_27_02-distill_memory_ViT-B-16-model_ViT-B-16-lr_0.0005-b_20-j_8-p_amp_bf16-loss_cosine/checkpoints/epoch_23.pt" \
#     --val-data="/projects/0/prjs1465/ShareGPT4V/wds_sharegpt4v/val_1/000000.tar" \
#     --dataset_name "sharegpt4v" \
#     --val-num-samples 1000 \
#     --dataset-type=webdataset \
#     --use-memory \
#     --model ViT-B-16 \
#     --pretrained "openai" \
#     --precision amp_bf16 \
#     --batch-size=16  \
#     --workers=2 \
#     --epochs=0 \
#     --logs="/projects/0/prjs1465/logs/teacher_baseline_eval" \
#     --report-to "none" \